name: Build actus

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_NAME: ssccsorg/actus

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and test
        run: |
          docker buildx build --load \
            --cache-from type=gha,scope=shared-actus \
            --cache-to type=gha,mode=min,scope=shared-actus \
            --target full \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            -f Dockerfile .
        shell: bash
